import Foundation

/// Defines the visual layout arrangement for assembling two radicals into a Kanji.
public enum RadicalLayout: String, Codable, Sendable {
    case horizontal // Left-Right (hen & tsukuri)
    case vertical   // Top-Bottom (kanmuri & ashi)
    case enclosing  // Outer-Inner (kamae & tare)
}

/// Represents a single stage in the 50-stage progressive Radical Fusion puzzle campaign.
public struct RadicalFusionPuzzle: Identifiable, Codable, Sendable, Hashable {
    public let id: Int
    public let stageTitle: String
    public let pieceA: String
    public let pieceALabel: String
    public let pieceB: String
    public let pieceBLabel: String
    public let layout: RadicalLayout
    public let resultKanji: String
    public let resultMeaning: String
    public let onyomi: String
    public let kunyomi: String
    public let compoundExample: String
    public let explanation: String

    public init(
        id: Int,
        stageTitle: String,
        pieceA: String,
        pieceALabel: String,
        pieceB: String,
        pieceBLabel: String,
        layout: RadicalLayout = .horizontal,
        resultKanji: String,
        resultMeaning: String,
        onyomi: String,
        kunyomi: String,
        compoundExample: String,
        explanation: String
    ) {
        self.id = id
        self.stageTitle = stageTitle
        self.pieceA = pieceA
        self.pieceALabel = pieceALabel
        self.pieceB = pieceB
        self.pieceBLabel = pieceBLabel
        self.layout = layout
        self.resultKanji = resultKanji
        self.resultMeaning = resultMeaning
        self.onyomi = onyomi
        self.kunyomi = kunyomi
        self.compoundExample = compoundExample
        self.explanation = explanation
    }
}

/// Static registry of all 50 curated Radical Fusion campaign stages.
public struct RadicalFusionData: Sendable {
    public static let all50: [RadicalFusionPuzzle] = [
        // 1 - 10: Foundational Left-Right and Basic Elements
        RadicalFusionPuzzle(
            id: 1,
            stageTitle: "Stage 1: Sun & Moon",
            pieceA: "日",
            pieceALabel: "Sun / Day",
            pieceB: "月",
            pieceBLabel: "Moon / Month",
            layout: .horizontal,
            resultKanji: "明",
            resultMeaning: "Bright / Clarity",
            onyomi: "メイ",
            kunyomi: "あかるい",
            compoundExample: "明日 (あした - Tomorrow)",
            explanation: "When the brilliant sun (日) and glowing moon (月) join together, they illuminate the world with brightness (明)."
        ),
        RadicalFusionPuzzle(
            id: 2,
            stageTitle: "Stage 2: Double Trees",
            pieceA: "木",
            pieceALabel: "Tree",
            pieceB: "木",
            pieceBLabel: "Tree",
            layout: .horizontal,
            resultKanji: "林",
            resultMeaning: "Woods / Grove",
            onyomi: "リン",
            kunyomi: "はやし",
            compoundExample: "森林 (しんりん - Forest)",
            explanation: "Two trees (木 + 木) standing side-by-side grow into a peaceful grove or woods (林)."
        ),
        RadicalFusionPuzzle(
            id: 3,
            stageTitle: "Stage 3: Mouth & Ten",
            pieceA: "口",
            pieceALabel: "Mouth",
            pieceB: "十",
            pieceBLabel: "Ten / Fullness",
            layout: .horizontal,
            resultKanji: "叶",
            resultMeaning: "Grant / Fulfill",
            onyomi: "キョウ",
            kunyomi: "かなう",
            compoundExample: "叶える (かなえる - To fulfill a dream)",
            explanation: "When words spoken by the mouth (口) align with complete perfection (十), your wish is granted (叶)."
        ),
        RadicalFusionPuzzle(
            id: 4,
            stageTitle: "Stage 4: Person & Tree",
            pieceA: "人",
            pieceALabel: "Person",
            pieceB: "木",
            pieceBLabel: "Tree",
            layout: .horizontal,
            resultKanji: "休",
            resultMeaning: "Rest / Break",
            onyomi: "キュウ",
            kunyomi: "やすむ",
            compoundExample: "休日 (きゅうじつ - Holiday)",
            explanation: "A weary person (人) leaning peacefully against the trunk of a tree (木) takes a well-deserved rest (休)."
        ),
        RadicalFusionPuzzle(
            id: 5,
            stageTitle: "Stage 5: Woman & Child",
            pieceA: "女",
            pieceALabel: "Woman",
            pieceB: "子",
            pieceBLabel: "Child",
            layout: .horizontal,
            resultKanji: "好",
            resultMeaning: "Like / Fondness",
            onyomi: "コウ",
            kunyomi: "すき",
            compoundExample: "好物 (こうぶつ - Favorite food)",
            explanation: "The unconditional affection between a mother (女) holding her infant child (子) expresses genuine fondness and liking (好)."
        ),
        RadicalFusionPuzzle(
            id: 6,
            stageTitle: "Stage 6: Field & Power",
            pieceA: "田",
            pieceALabel: "Field",
            pieceB: "力",
            pieceBLabel: "Power / Strength",
            layout: .vertical,
            resultKanji: "男",
            resultMeaning: "Man / Male",
            onyomi: "ダン",
            kunyomi: "おとこ",
            compoundExample: "男子 (だんし - Boy / Young man)",
            explanation: "Historically, physical strength and power (力) exerted working the rice fields (田) symbolized the man (男)."
        ),
        RadicalFusionPuzzle(
            id: 7,
            stageTitle: "Stage 7: Words & Tongue",
            pieceA: "言",
            pieceALabel: "Words / Speech",
            pieceB: "舌",
            pieceBLabel: "Tongue",
            layout: .horizontal,
            resultKanji: "話",
            resultMeaning: "Talk / Conversation",
            onyomi: "ワ",
            kunyomi: "はなす",
            compoundExample: "会話 (かいわ - Conversation)",
            explanation: "Using the tongue (舌) to articulate expressive spoken words (言) creates natural conversation and speech (話)."
        ),
        RadicalFusionPuzzle(
            id: 8,
            stageTitle: "Stage 8: Gate & Sun",
            pieceA: "門",
            pieceALabel: "Gate",
            pieceB: "日",
            pieceBLabel: "Sun / Light",
            layout: .enclosing,
            resultKanji: "間",
            resultMeaning: "Interval / Space",
            onyomi: "カン",
            kunyomi: "あいだ",
            compoundExample: "時間 (じかん - Time / Hours)",
            explanation: "Sunlight (日) streaming through the slit between two closed gate doors (門) reveals an opening, interval, or space (間)."
        ),
        RadicalFusionPuzzle(
            id: 9,
            stageTitle: "Stage 9: Thread & Meeting",
            pieceA: "糸",
            pieceALabel: "Thread",
            pieceB: "会",
            pieceBLabel: "Meet / Gather",
            layout: .horizontal,
            resultKanji: "絵",
            resultMeaning: "Picture / Painting",
            onyomi: "カイ",
            kunyomi: "え",
            compoundExample: "絵画 (かいが - Painting)",
            explanation: "Bringing colored threads together in an orderly gathering (糸 + 会) weaves an elaborate picture or artwork (絵)."
        ),
        RadicalFusionPuzzle(
            id: 10,
            stageTitle: "Stage 10: Tree & Measure",
            pieceA: "木",
            pieceALabel: "Tree",
            pieceB: "寸",
            pieceBLabel: "Measurement",
            layout: .horizontal,
            resultKanji: "村",
            resultMeaning: "Village",
            onyomi: "ソン",
            kunyomi: "むら",
            compoundExample: "農村 (のうそん - Agricultural village)",
            explanation: "A measured division of land marked by bordering trees (木 + 寸) defines a rural village (村)."
        ),

        // 11 - 20: Food, Nature, and Perception
        RadicalFusionPuzzle(
            id: 11,
            stageTitle: "Stage 11: Fish & Sheep",
            pieceA: "魚",
            pieceALabel: "Fish",
            pieceB: "羊",
            pieceBLabel: "Sheep",
            layout: .horizontal,
            resultKanji: "鮮",
            resultMeaning: "Fresh / Vivid",
            onyomi: "セン",
            kunyomi: "あざやか",
            compoundExample: "新鮮 (しんせん - Fresh)",
            explanation: "Pairing newly caught fish (魚) with tender young sheep (羊) symbolizes the pinnacle of culinary freshness (鮮)."
        ),
        RadicalFusionPuzzle(
            id: 12,
            stageTitle: "Stage 12: Hand & Nail",
            pieceA: "扌",
            pieceALabel: "Hand",
            pieceB: "丁",
            pieceBLabel: "Nail / Strike",
            layout: .horizontal,
            resultKanji: "打",
            resultMeaning: "Hit / Strike",
            onyomi: "ダ",
            kunyomi: "うつ",
            compoundExample: "打者 (だしゃ - Batter / Hitter)",
            explanation: "A hand (扌) driving down upon a nail (丁) represents the decisive action to hit or strike (打)."
        ),
        RadicalFusionPuzzle(
            id: 13,
            stageTitle: "Stage 13: Sound & Heart",
            pieceA: "音",
            pieceALabel: "Sound",
            pieceB: "心",
            pieceBLabel: "Heart / Mind",
            layout: .vertical,
            resultKanji: "意",
            resultMeaning: "Meaning / Intention",
            onyomi: "イ",
            kunyomi: "こころ",
            compoundExample: "意味 (いみ - Meaning)",
            explanation: "The subtle sound (音) resonating deep inside one's heart (心) gives voice to true thought, intention, and meaning (意)."
        ),
        RadicalFusionPuzzle(
            id: 14,
            stageTitle: "Stage 14: Perish & Heart",
            pieceA: "亡",
            pieceALabel: "Perish / Lost",
            pieceB: "心",
            pieceBLabel: "Heart / Memory",
            layout: .vertical,
            resultKanji: "忘",
            resultMeaning: "Forget",
            onyomi: "ボウ",
            kunyomi: "わすれる",
            compoundExample: "忘年会 (ぼうねんかい - Year-end party)",
            explanation: "When an impression perishes or is lost (亡) from the awareness of the heart (心), you forget it (忘)."
        ),
        RadicalFusionPuzzle(
            id: 15,
            stageTitle: "Stage 15: Mouth & Beg",
            pieceA: "口",
            pieceALabel: "Mouth",
            pieceB: "乞",
            pieceBLabel: "Beg / Ask",
            layout: .horizontal,
            resultKanji: "吃",
            resultMeaning: "Gasp / Astonish",
            onyomi: "キツ",
            kunyomi: "どもる",
            compoundExample: "吃驚 (びっくり - Surprise / Astonishment)",
            explanation: "Opening your mouth (口) gasping in search of air (乞) portrays pure sudden surprise and astonishment (吃)."
        ),
        RadicalFusionPuzzle(
            id: 16,
            stageTitle: "Stage 16: Mountain & Stone",
            pieceA: "山",
            pieceALabel: "Mountain",
            pieceB: "石",
            pieceBLabel: "Stone",
            layout: .vertical,
            resultKanji: "岩",
            resultMeaning: "Rock / Boulder",
            onyomi: "ガン",
            kunyomi: "いわ",
            compoundExample: "岩石 (がんせき - Rock)",
            explanation: "Heavy stones (石) quarried from high rugged mountains (山) form massive solid boulders and rocks (岩)."
        ),
        RadicalFusionPuzzle(
            id: 17,
            stageTitle: "Stage 17: Sun & Temple",
            pieceA: "日",
            pieceALabel: "Sun",
            pieceB: "寺",
            pieceBLabel: "Temple",
            layout: .horizontal,
            resultKanji: "時",
            resultMeaning: "Time / Hour",
            onyomi: "ジ",
            kunyomi: "とき",
            compoundExample: "時計 (とけい - Clock / Watch)",
            explanation: "Tracking the journey of the sun (日) alongside bells struck at regular intervals by a temple (寺) marks the passing of time (時)."
        ),
        RadicalFusionPuzzle(
            id: 18,
            stageTitle: "Stage 18: Tree & Every",
            pieceA: "木",
            pieceALabel: "Tree",
            pieceB: "毎",
            pieceBLabel: "Every / Abundant",
            layout: .horizontal,
            resultKanji: "梅",
            resultMeaning: "Plum",
            onyomi: "バイ",
            kunyomi: "うめ",
            compoundExample: "梅雨 (つゆ / ばいう - Rainy season)",
            explanation: "The flowering tree (木) that blooms reliably every single spring (毎) is the fragrant Japanese plum (梅)."
        ),
        RadicalFusionPuzzle(
            id: 19,
            stageTitle: "Stage 19: Water & Blue",
            pieceA: "氵",
            pieceALabel: "Water",
            pieceB: "青",
            pieceBLabel: "Blue / Clear",
            layout: .horizontal,
            resultKanji: "清",
            resultMeaning: "Pure / Clean",
            onyomi: "セイ",
            kunyomi: "きよい",
            compoundExample: "清潔 (せいけつ - Cleanliness)",
            explanation: "Flowing spring water (氵) as pristine, blue, and transparent as the morning sky (青) is sparkling pure and clean (清)."
        ),
        RadicalFusionPuzzle(
            id: 20,
            stageTitle: "Stage 20: Fire & Nail",
            pieceA: "火",
            pieceALabel: "Fire",
            pieceB: "丁",
            pieceBLabel: "Stand / Nail",
            layout: .horizontal,
            resultKanji: "灯",
            resultMeaning: "Lamp / Light",
            onyomi: "トウ",
            kunyomi: "ひ",
            compoundExample: "点灯 (てんとう - Lighting up a lamp)",
            explanation: "A small flame of fire (火) perched on top of a slender metal stand (丁) provides a guiding lamp light (灯)."
        ),

        // 21 - 30: Society, Movement, and Crafts
        RadicalFusionPuzzle(
            id: 21,
            stageTitle: "Stage 21: Eye & Needle",
            pieceA: "目",
            pieceALabel: "Eye",
            pieceB: "亡",
            pieceBLabel: "Perish / Hidden",
            layout: .horizontal,
            resultKanji: "盲",
            resultMeaning: "Blind",
            onyomi: "モウ",
            kunyomi: "めくら",
            compoundExample: "盲点 (もうてん - Blind spot)",
            explanation: "When sight perishes (亡) from within the eye (目), vision is impaired (盲)."
        ),
        RadicalFusionPuzzle(
            id: 22,
            stageTitle: "Stage 22: Sun & Stand",
            pieceA: "日",
            pieceALabel: "Sun",
            pieceB: "立",
            pieceBLabel: "Stand",
            layout: .vertical,
            resultKanji: "音",
            resultMeaning: "Sound / Note",
            onyomi: "オン",
            kunyomi: "おと",
            compoundExample: "音楽 (おんがく - Music)",
            explanation: "When tone stands upright (立) clear as day (日), it becomes distinct musical sound (音)."
        ),
        RadicalFusionPuzzle(
            id: 23,
            stageTitle: "Stage 23: Fire & Field",
            pieceA: "火",
            pieceALabel: "Fire",
            pieceB: "田",
            pieceBLabel: "Field",
            layout: .horizontal,
            resultKanji: "畑",
            resultMeaning: "Cultivated Crop Field",
            onyomi: "はた",
            kunyomi: "はたけ",
            compoundExample: "麦畑 (むぎばたけ - Wheat field)",
            explanation: "Using controlled fire (火) to clear dry land for farming dry crops (田) creates a productive dry field (畑)."
        ),
        RadicalFusionPuzzle(
            id: 24,
            stageTitle: "Stage 24: Gold & Same",
            pieceA: "金",
            pieceALabel: "Metal / Gold",
            pieceB: "同",
            pieceBLabel: "Same / Together",
            layout: .horizontal,
            resultKanji: "銅",
            resultMeaning: "Copper / Bronze",
            onyomi: "ドウ",
            kunyomi: "あかがね",
            compoundExample: "銅メダル (どうメダル - Bronze medal)",
            explanation: "A metal (金) that shares similar properties and alloys with other common elements (同) is copper (銅)."
        ),
        RadicalFusionPuzzle(
            id: 25,
            stageTitle: "Stage 25: Rice & White",
            pieceA: "米",
            pieceALabel: "Rice",
            pieceB: "白",
            pieceBLabel: "White",
            layout: .horizontal,
            resultKanji: "粕",
            resultMeaning: "Residue / Lees",
            onyomi: "ハク",
            kunyomi: "かす",
            compoundExample: "酒粕 (さけかす - Sake lees)",
            explanation: "The white sediment (白) left behind after fermenting steamed rice (米) into sake is flavorful lees (粕)."
        ),
        RadicalFusionPuzzle(
            id: 26,
            stageTitle: "Stage 26: Water & Sky",
            pieceA: "氵",
            pieceALabel: "Water",
            pieceB: "天",
            pieceBLabel: "Heavens / Sky",
            layout: .horizontal,
            resultKanji: "添",
            resultMeaning: "Accompany / Add",
            onyomi: "テン",
            kunyomi: "そえる",
            compoundExample: "添付 (てんぷ - Email attachment)",
            explanation: "Water (氵) reaching upward to complement the heavens (天) accompanies and adds completeness (添)."
        ),
        RadicalFusionPuzzle(
            id: 27,
            stageTitle: "Stage 27: Sun & Blue",
            pieceA: "日",
            pieceALabel: "Sun",
            pieceB: "青",
            pieceBLabel: "Blue",
            layout: .horizontal,
            resultKanji: "晴",
            resultMeaning: "Clear Sky / Sunny",
            onyomi: "セイ",
            kunyomi: "はれる",
            compoundExample: "快晴 (かいせい - Clear weather)",
            explanation: "The bright sun (日) shining unimpeded across a clear blue sky (青) promises sunny, fine weather (晴)."
        ),
        RadicalFusionPuzzle(
            id: 28,
            stageTitle: "Stage 28: Rain & Mutual",
            pieceA: "雨",
            pieceALabel: "Rain / Clouds",
            pieceB: "相",
            pieceBLabel: "Mutual / Aspect",
            layout: .vertical,
            resultKanji: "霜",
            resultMeaning: "Frost",
            onyomi: "ソウ",
            kunyomi: "しも",
            compoundExample: "初霜 (はつしも - First winter frost)",
            explanation: "Cold moisture from the rainy sky (雨) interacting with cold surface trees (相) coats the earth in morning frost (霜)."
        ),
        RadicalFusionPuzzle(
            id: 29,
            stageTitle: "Stage 29: Hand & Root",
            pieceA: "扌",
            pieceALabel: "Hand",
            pieceB: "本",
            pieceBLabel: "Origin / Book",
            layout: .horizontal,
            resultKanji: "体",
            resultMeaning: "Body",
            onyomi: "タイ",
            kunyomi: "からだ",
            compoundExample: "体力 (たいりょく - Physical strength)",
            explanation: "A person's limbs and hands aligned with the origin of life (人/扌 + 本) form the living human body (体)."
        ),
        RadicalFusionPuzzle(
            id: 30,
            stageTitle: "Stage 30: Words & Complete",
            pieceA: "言",
            pieceALabel: "Words",
            pieceB: "成",
            pieceBLabel: "Achieve / Become",
            layout: .horizontal,
            resultKanji: "誠",
            resultMeaning: "Sincerity / Truth",
            onyomi: "セイ",
            kunyomi: "まこと",
            compoundExample: "誠実 (せいじつ - Sincere / Honest)",
            explanation: "When words spoken (言) are faithfully achieved and fulfilled (成), you demonstrate absolute sincerity (誠)."
        ),

        // 31 - 40: Mind, Structures, and Actions
        RadicalFusionPuzzle(
            id: 31,
            stageTitle: "Stage 31: Heart & Green",
            pieceA: "忄",
            pieceALabel: "Heart",
            pieceB: "青",
            pieceBLabel: "Blue / Youth",
            layout: .horizontal,
            resultKanji: "情",
            resultMeaning: "Emotion / Feeling",
            onyomi: "ジョウ",
            kunyomi: "なさけ",
            compoundExample: "感情 (かんじょう - Emotion)",
            explanation: "The fresh, vibrant pulse of the heart (忄 + 青) expresses deep human emotion and sympathy (情)."
        ),
        RadicalFusionPuzzle(
            id: 32,
            stageTitle: "Stage 32: Mountain & Wind",
            pieceA: "山",
            pieceALabel: "Mountain",
            pieceB: "風",
            pieceBLabel: "Wind",
            layout: .horizontal,
            resultKanji: "嵐",
            resultMeaning: "Storm / Tempest",
            onyomi: "ラン",
            kunyomi: "あらし",
            compoundExample: "砂嵐 (すなあらし - Sandstorm)",
            explanation: "Fierce winds (風) sweeping violently through the high mountain peaks (山) unleash a tempest storm (嵐)."
        ),
        RadicalFusionPuzzle(
            id: 33,
            stageTitle: "Stage 33: Mouth & Bird",
            pieceA: "口",
            pieceALabel: "Mouth",
            pieceB: "鳥",
            pieceBLabel: "Bird",
            layout: .horizontal,
            resultKanji: "鳴",
            resultMeaning: "Chirp / Cry",
            onyomi: "メイ",
            kunyomi: "なく",
            compoundExample: "悲鳴 (ひめい - Scream / Cry)",
            explanation: "Sound singing continuously from the mouth of a wild bird (口 + 鳥) is joyful chirping (鳴)."
        ),
        RadicalFusionPuzzle(
            id: 34,
            stageTitle: "Stage 34: Thread & White",
            pieceA: "糸",
            pieceALabel: "Thread",
            pieceB: "白",
            pieceBLabel: "White / Silk",
            layout: .horizontal,
            resultKanji: "絹",
            resultMeaning: "Silk",
            onyomi: "ケン",
            kunyomi: "きぬ",
            compoundExample: "絹織物 (きぬおりもの - Silk fabric)",
            explanation: "Fine lustrous threads spun from cocoon casing (糸 + 口/白) weave soft, elegant pure silk (絹)."
        ),
        RadicalFusionPuzzle(
            id: 35,
            stageTitle: "Stage 35: Sun & Center",
            pieceA: "日",
            pieceALabel: "Sun",
            pieceB: "央",
            pieceBLabel: "Center",
            layout: .horizontal,
            resultKanji: "映",
            resultMeaning: "Reflect / Project",
            onyomi: "エイ",
            kunyomi: "うつる",
            compoundExample: "映画 (えいが - Movie / Film)",
            explanation: "Light from the sun (日) beaming straight onto the center stage (央) reflects and projects a movie image (映)."
        ),
        RadicalFusionPuzzle(
            id: 36,
            stageTitle: "Stage 36: Bamboo & Eye",
            pieceA: "⺮",
            pieceALabel: "Bamboo",
            pieceB: "目",
            pieceBLabel: "Eye",
            layout: .vertical,
            resultKanji: "箱",
            resultMeaning: "Box / Chest",
            onyomi: "ソウ",
            kunyomi: "はこ",
            compoundExample: "本箱 (ほんばこ - Bookcase / Book box)",
            explanation: "A container crafted from woven bamboo slats (⺮) inspected closely by the eye (相/目) is a storage box (箱)."
        ),
        RadicalFusionPuzzle(
            id: 37,
            stageTitle: "Stage 37: Rice & Strength",
            pieceA: "米",
            pieceALabel: "Rice / Grain",
            pieceB: "分",
            pieceBLabel: "Divide",
            layout: .vertical,
            resultKanji: "粉",
            resultMeaning: "Flour / Powder",
            onyomi: "フン",
            kunyomi: "こな",
            compoundExample: "小麦粉 (こむぎこ - Wheat flour)",
            explanation: "Grinding grains of rice (米) into finely divided particles (分) creates powder or flour (粉)."
        ),
        RadicalFusionPuzzle(
            id: 38,
            stageTitle: "Stage 38: Words & Temple",
            pieceA: "言",
            pieceALabel: "Words",
            pieceB: "寺",
            pieceBLabel: "Temple",
            layout: .horizontal,
            resultKanji: "詩",
            resultMeaning: "Poem / Poetry",
            onyomi: "シ",
            kunyomi: "うた",
            compoundExample: "詩人 (しじん - Poet)",
            explanation: "Deep, solemn words (言) recited meditatively in temple courtyards (寺) become beautiful poetry (詩)."
        ),
        RadicalFusionPuzzle(
            id: 39,
            stageTitle: "Stage 39: Tree & Wind",
            pieceA: "木",
            pieceALabel: "Tree",
            pieceB: "風",
            pieceBLabel: "Wind",
            layout: .horizontal,
            resultKanji: "楓",
            resultMeaning: "Maple Tree",
            onyomi: "フウ",
            kunyomi: "かえで",
            compoundExample: "紅葉 (もみじ / 楓 - Autumn maple)",
            explanation: "The elegant forest tree (木) whose fluttering autumn leaves dance gracefully in the wind (風) is the maple (楓)."
        ),
        RadicalFusionPuzzle(
            id: 40,
            stageTitle: "Stage 40: Hand & Hold",
            pieceA: "扌",
            pieceALabel: "Hand",
            pieceB: "持",
            pieceBLabel: "Keep / Hold",
            layout: .horizontal,
            resultKanji: "指",
            resultMeaning: "Finger / Point",
            onyomi: "シ",
            kunyomi: "ゆび",
            compoundExample: "指示 (しじ - Instruction / Direction)",
            explanation: "The versatile extremity of the hand (扌) used to point toward intentions (旨) is your finger (指)."
        ),

        // 41 - 50: Advanced Compounds, Culture & Mastery
        RadicalFusionPuzzle(
            id: 41,
            stageTitle: "Stage 41: Person & Word",
            pieceA: "亻",
            pieceALabel: "Person",
            pieceB: "言",
            pieceBLabel: "Word",
            layout: .horizontal,
            resultKanji: "信",
            resultMeaning: "Trust / Faith",
            onyomi: "シン",
            kunyomi: "しんじる",
            compoundExample: "信用 (しんよう - Confidence / Trust)",
            explanation: "When a person (亻) stands firmly by their given word (言), they inspire unwavering faith and trust (信)."
        ),
        RadicalFusionPuzzle(
            id: 42,
            stageTitle: "Stage 42: Water & Each",
            pieceA: "氵",
            pieceALabel: "Water",
            pieceB: "各",
            pieceBLabel: "Each / Separate",
            layout: .horizontal,
            resultKanji: "洛",
            resultMeaning: "Ancient Capital City",
            onyomi: "ラク",
            kunyomi: "みやこ",
            compoundExample: "上洛 (じょうらく - Journeying to Kyoto)",
            explanation: "Waterways (氵) converging where travelers from each province gather (各) form a legendary imperial capital (洛)."
        ),
        RadicalFusionPuzzle(
            id: 43,
            stageTitle: "Stage 43: Hand & Eye",
            pieceA: "手",
            pieceALabel: "Hand",
            pieceB: "目",
            pieceBLabel: "Eye",
            layout: .vertical,
            resultKanji: "看",
            resultMeaning: "Watch / Care",
            onyomi: "カン",
            kunyomi: "みる",
            compoundExample: "看板 (かんばん - Signboard / Billboard)",
            explanation: "Shading your eye (目) with your hand (手) to gaze intently into the distance means to watch or observe (看)."
        ),
        RadicalFusionPuzzle(
            id: 44,
            stageTitle: "Stage 44: Gold & Heavy",
            pieceA: "金",
            pieceALabel: "Metal",
            pieceB: "重",
            pieceBLabel: "Heavy",
            layout: .horizontal,
            resultKanji: "鐘",
            resultMeaning: "Bell / Chime",
            onyomi: "ショウ",
            kunyomi: "かね",
            compoundExample: "晩鐘 (ばんしょう - Evening temple bell)",
            explanation: "Cast from heavy, precious metal alloys (金 + 重), this grand instrument rings out as a temple bell (鐘)."
        ),
        RadicalFusionPuzzle(
            id: 45,
            stageTitle: "Stage 45: Cart & Military",
            pieceA: "車",
            pieceALabel: "Vehicle",
            pieceB: "軍",
            pieceBLabel: "Army / Troops",
            layout: .horizontal,
            resultKanji: "輝",
            resultMeaning: "Radiate / Sparkle",
            onyomi: "キ",
            kunyomi: "かがやく",
            compoundExample: "光輝 (こうき - Splendor / Brightness)",
            explanation: "Triumphant banners surrounding chariot processions (光/軍 + 車) radiate brilliance and sparkle (輝)."
        ),
        RadicalFusionPuzzle(
            id: 46,
            stageTitle: "Stage 46: Sun & Moon in Woods",
            pieceA: "木",
            pieceALabel: "Tree",
            pieceB: "林",
            pieceBLabel: "Woods",
            layout: .vertical,
            resultKanji: "森",
            resultMeaning: "Deep Forest",
            onyomi: "シン",
            kunyomi: "もり",
            compoundExample: "森林浴 (しんりんよく - Forest bathing)",
            explanation: "Adding yet another tree (木) above a woods (林) produces a thick, lush, towering deep forest (森)."
        ),
        RadicalFusionPuzzle(
            id: 47,
            stageTitle: "Stage 47: Water & Sheep",
            pieceA: "氵",
            pieceALabel: "Water",
            pieceB: "羊",
            pieceBLabel: "Sheep",
            layout: .horizontal,
            resultKanji: "洋",
            resultMeaning: "Ocean / Western",
            onyomi: "ヨウ",
            kunyomi: "うみ",
            compoundExample: "太平洋 (たいへいよう - Pacific Ocean)",
            explanation: "Endless vast waters (氵) rolling as broad and expansive as a great flock of sheep (羊) span the open ocean (洋)."
        ),
        RadicalFusionPuzzle(
            id: 48,
            stageTitle: "Stage 48: Words & Plan",
            pieceA: "言",
            pieceALabel: "Words",
            pieceB: "十",
            pieceBLabel: "Ten / Complete",
            layout: .horizontal,
            resultKanji: "計",
            resultMeaning: "Measure / Plan",
            onyomi: "ケイ",
            kunyomi: "はかる",
            compoundExample: "計画 (けいかく - Plan / Project)",
            explanation: "Speaking measured words (言) while accurately counting in tens (十) produces a careful plan or calculation (計)."
        ),
        RadicalFusionPuzzle(
            id: 49,
            stageTitle: "Stage 49: Gate & Ear",
            pieceA: "門",
            pieceALabel: "Gate",
            pieceB: "耳",
            pieceBLabel: "Ear",
            layout: .enclosing,
            resultKanji: "聞",
            resultMeaning: "Hear / Listen",
            onyomi: "ブン",
            kunyomi: "きく",
            compoundExample: "新聞 (しんぶん - Newspaper)",
            explanation: "Pressing your ear (耳) up close against the gateway (門) allows you to clearly hear news and listen (聞)."
        ),
        RadicalFusionPuzzle(
            id: 50,
            stageTitle: "Stage 50: Sun & Bright Sky",
            pieceA: "日",
            pieceALabel: "Sun",
            pieceB: "星",
            pieceBLabel: "Stars",
            layout: .vertical,
            resultKanji: "晶",
            resultMeaning: "Crystal / Pure Light",
            onyomi: "ショウ",
            kunyomi: "すいしょう",
            compoundExample: "水晶 (すいしょう - Quartz crystal)",
            explanation: "Three blazing suns (日 + 日 + 日) radiating pure crystalline light in sacred harmony symbolize the sparkling crystal (晶)."
        )
    ]
}
